### ISSUE TITLE
Please provide examples on how to use in code

### ISSUE THREAD

**Issue by nonetrix** [lukehsiao/randselect#19]
I want to select a random file in a directory in a music player I'm working but I can't find any examples on how I would use this in my rust code sorry if I am missing something I'm not very good with rust yet tbh

**Comment by lukehsiao** [comment]
This is just meant as a CLI tool, and not to be used as a library. So, I wouldn't try and use this as a dependency for something you're building. 

That said, if you want to select a random file in a directory, the whole program is just a couple hundred lines of code. You can use this tool's code as an example and implement it yourself. The file you want to look at is here:

https://github.com/lukehsiao/randselect/blob/main/src/lib.rs
